name: Terraform CI - Plan

on:
  push:
    branches:
      - "feature/3rdrg_add"

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  terraform-plan:

    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Parent module

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan